### ISSUE TITLE
tsp members can't make requests

### ISSUE THREAD

**Issue by tsdgeos** [openSUSE/travel-support-program#17]
We are evaluating this software at KDE and have seen that if your user is a tsp_member it seems it can't create requests for travel support.

We need that since eventually people on the support commitee need to ask for travel support too.

**Comment by ancorgs** [comment]
I'm currently traveling with very occasional internet access. Back on Monday.

Anyway, the application was implemented with a main idea: the rules or the exact workflow of the requests can change at any point in time and adapting the application should be a matter of minutes.

For example, removing that restriction should be straightforward just changing the file app/models/ability.rb that should be very easy to understand for any programmer (even not knowing Ruby).

More info on Monday :)

**Comment by ancorgs** [comment]
As said, the permissions are isolated in the Ability.rb file. It should be fairly easy even to create a table in the database and make them 100% configurable. It was even a Google Summer of Code project about it which resulted in https://github.com/openSUSE/travel-support-program/pull/13, not merged for some minor reasons.

To address the requested change without going that far, it would be enough to perform 2 changes:

a) Adapt the permissions of the "tsp" role starting here https://github.com/openSUSE/travel-support-program/blob/master/app/models/ability.rb#L138 using the requester permissions as inspiration.
b) Most likely, adapt the workflow in the TravelSponsorship model here https://github.com/openSUSE/travel-support-program/blob/master/app/models/travel_sponsorship.rb#L20

As you can see, the state machines (TravelSponsorship, Reimbursement, Shipment) workflows (steps, permissions for each step, reminders, etc.) are also configured in some kind of DSL. Like the general permissions on Ability.rb, it should be easy to extract that part to the database or some configuration file in order to make it more flexible.

**Comment by ancorgs** [comment]
If you decide it's worth the effort, we can coordinate to implement the needed changes to make the application more configurable. We haven't developed it further because it already fulfills our needs but we tried to leave everything in place to make the next step possible. With some extra manpower, I'd be glad to re-start development.

**Comment by tsdgeos** [comment]
I'm not a ruby devel, i'll try to see if the person that deployed the app can help doing the changes you suggest.

**Comment by tsdgeos** [comment]
I've been able to do random enough copy and paste to make it work, i guess we can close it since you don't seem to think this makes sense for upstream.

**Comment by ancorgs** [comment]
In fact, I'm not against implementing this in upstream. If it makes the application more appealing to you, I'm fine with it. As soon as TSP members cannot approve their own requests (needing another member to do so), which in my opinion makes perfect sense for any organization, it will be fine for openSUSE as well.

So I'll try to implement it this week. Should be quite straightforward.

**Comment by tsdgeos** [comment]
This is my poor's man solution for allowing tsp members to do their own requests (needing another member to approve is done at the social level) and also for removing shipments since we do not have that. https://paste.kde.org/poqs9xsj0 (will last a year)

**Comment by ancorgs** [comment]
This will be the next thing to take a look to.

**Comment by ancorgs** [comment]
I will use this as an opportunity to do something that is long due: remove `:requester` as a role (I know what I mean).

**Comment by tsdgeos** [comment]
maybe you can make roles to be non exclusive? We have not found the problem yet but i think we'll also need some of the tspmembers to be administratives so they can actually mark the transaction as done since some of them can

maybe we could have

tspmember:1
administrative: 2
assistant: 4

so you can have things like 3 = tspmember + administrative
5= tspmember + assistant (not sure this one makes sense but i guess you know what i mean)

**Comment by ancorgs** [comment]
Let's address the problems one by one :wink: 

First of all, the application had a real design problem: being a requester was considered a role and only users with such role were able to ask for support. This is fixed now in the `requester_is_not_a_role` branch of the repo, in which everybody can create requests and reimbursements despite the user's role.
https://github.com/openSUSE/travel-support-program/tree/requester_is_not_a_role

The `requester` concept is still used in the permissions system, but not longer as a regular role but with its (obvious) real meaning. The permissions regarding your own requests are defined by that `requester` flag, the permissions for any other request are defined by your role. That means that a TSP member can approve any request but his/her own ones. He/she needs the approval from another TSP member. Same principle applies to all the state transitions.

I would appreciate if you could test that branch before merging it to master. I spent a lot of time adjusting the test suite, but did almost no manual test.

About the other idea: making it possible for a user to have several roles (like TSP member + administrative), let's open a separate issue on github for it. But it's actually much much easier to implement now that we refactored the requester thingy. Probably just a matter of minutes to implement... and a whole day adapting the automated test suite and creating new tests :wink:

**Comment by tsdgeos** [comment]
There is a problem in here which is that when a tspmember creates a travel support request and does not submit it immediately, the travel support is hard to find since the left bar "Travel support requests" link links only to the submitted travel requests, which made sense when the tsp members could only approve other people ones but now that they can also have own that are unapproved i think it makes sense for them to just go to http://localhost:3000/travel_sponsorships instead of http://localhost:3000/travel_sponsorships?q[state_in][]=submitted

This was part of my huge diff too. What do you think?

**Comment by ancorgs** [comment]
Well, actually I expect the TSP members to be familiar enough with the application and the filters and I also expect TSP members applying for support to be an exception, something that happens rarely.

Taking that into account, I would rather keep the day-to-day case agile and straightforward, even if that means that TSP members applying for support need to take an additional step.

On the other hand, the application sends mail reminders about inactive requests and reimbursements in "incomplete" state (including the direct url, of course), just in case the TSP member forgets to submit (something, again, I don't expect from somebody familiar with the application).

**Comment by tsdgeos** [comment]
Ok, i see your point. On the other hand our tspmembers are still not familiar enough with the system but i guess that can just be fixed by using it, so yeah the branch looks good to me.

**Comment by tsdgeos** [comment]
This can be marked as fixed now, right?

**Comment by ancorgs** [comment]
Right
